### ISSUE TITLE
Feature request: Add Avro as an output [file] format

### ISSUE THREAD

**Issue by pataquets** [SpamScope/mail-parser#10]
Thanks for this great piece of software.

Having Avro as an output file format to the command line tool would be awesome to use it with all sorts of big data tools. Looks like there is an official Avro lib for Python:
https://avro.apache.org/docs/current/gettingstartedpython.html

Usable via an ```--avro``` command line switch as is currently done with ```--json``` would be the way, IMHO.

I'm not sure of how much coupling between the actual parsing code and the JSON file writer there is. Will try to figure out from code, but I'm not very deep with Python. I'm currently just using the command line tool and and consuming it as JSON files.

TIA.

**Comment by pataquets** [comment]
Also found this (not sure how would fit): https://github.com/linkedin/python-avro-json-serializer

**Comment by fedelemantuano** [comment]
@pataquets thanks a lot for this suggestion. I will study this tool and then I will add feature. I'm tracking the changes here.

**Comment by fedelemantuano** [comment]
@pataquets: So Do I need to define a schema? And Will the output be a file `avro`?

**Comment by pataquets** [comment]
Not sure, but looks like it's needed, indeed. https://avro.apache.org/docs/current/index.html

**Comment by fedelemantuano** [comment]
For now I can't develop it, because the `mail` object can be change and so I have to manage the changes of schema. If more people will ask this function I will reopen this issue.
