### ISSUE TITLE
Multiple mail thread handling

### ISSUE THREAD

**Issue by Faran-Javaid** [SpamScope/mail-parser#101]
**Is your feature request related to a problem? Please describe.**
I have tried outlook .msg files having a whole conversation and I have faced an issue while getting subjects of all the emails present in a single file. It just returns some random value for the subject and rest of the information is also vague.

**Describe the solution you'd like**
It would be great if you could add a module to handle multi threaded emails having whole conversation. The ideal output will have a list or a dictionary having relative information of each email present in that .msg file in a sorted manner.

**Comment by fedelemantuano** [comment]
Can you attach an example?

**Comment by Faran-Javaid** [comment]
> Can you attach an example?

Hi @fedelemantuano Thanks for the quick response. I'm attaching an email for your reference. It is in zip format as github don't allows us to upload an .msg files directly. Just decompress it and you'll get the desired .msg file. Please let me know if you need any other assistance. Really looking forward to the update. [Re_ Assignment.zip](https://github.com/SpamScope/mail-parser/files/7570230/Re_.Assignment.zip)

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
