### ISSUE TITLE
When parsing eml attachment from Gmail, the attachment is being parsed as email instead as attachment

### ISSUE THREAD

**Issue by JasBeilin** [SpamScope/mail-parser#103]
**Describe the bug**
When parsing a message with an eml attachment (and the attachment contains an image, for example), the eml is parsed as a message as well instead of an attachment, so the image within is also being parsed as attachment of the external message.

**To Reproduce**
1. Create an email with an image attachment, send it to an available inbox.
2. forward the specific email from (1) as an attachment. 
3. run parse_from_bytes/ parse_from_file/ parse_from_str
4. See that the only attachment is the image, not the eml.

**Expected behavior**
I expect to see all attachments, including the eml file itself.

**Raw mail**

[testing eml parsing with attachment copy.eml.zip](https://github.com/SpamScope/mail-parser/files/7642261/testing.eml.parsing.with.attachment.copy.eml.zip)

**Environment:**
 - OS: Linux
 - Docker: [yes or no]
 - mail-parser version 3.15.0

**Additional context**
I used this code to parse it:
```
class mailParser:
    def run(self, raw_email):
        from mailparser import parse_from_bytes, parse_from_file
        return parse_from_bytes(bytes(raw_email))


parser = mailParser()
with open('testing eml parsing with attachment.eml', 'rb') as fhdl:
    raw_email = fhdl.read()
res = parser.run(raw_email)
print(res)
```

The results (one attachment- the inner image)
![image](https://user-images.githubusercontent.com/71636766/144430752-9db46586-b66c-436e-9a58-6f35f2096c73.png)

Possible solution:
I tried changing line 353 in the mailparser.py to ```if not p.is_multipart() or 'attachment' in p.get('content-disposition', '')```
So attachments will be able to be processes as attachments even if they are multipart/message.
and added this to line 279:
```                    elif 'attachment' in content_disposition:
                        is_attachment = True
                        payload = p.get_payload()
                        filename = dict(payload[0]._headers).get('Subject')
```
                       
                        
 As result, I got:
 
![image](https://user-images.githubusercontent.com/71636766/144439298-b6aa76b8-0106-4b74-8a16-87ae04fb6dc1.png)
(2 attachments, both the image and the eml file)

**Comment by sgeulette** [comment]
Hello,
I have the same problem...
Regards

**Comment by sgeulette** [comment]
Hello,
I have the same problem...
Regards

**Comment by fedelemantuano** [comment]
Thanks for this submission. I will check the issue.

**Comment by alfonsrv** [comment]
Seems like this is fixed with https://github.com/SpamScope/mail-parser/pull/89

**Comment by alfonsrv** [comment]
Seems like this is fixed with https://github.com/SpamScope/mail-parser/pull/89 – alternatively removing `not p.is_multipart()` in `mailparser.MailParser.parse:353` could work too. None of the tests break when it's removed.

Or using `not p.is_multipart() or p.get_filename() ...`.

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
