### ISSUE TITLE
Ignore warnings - Email content 'calendar' not handled

### ISSUE THREAD

**Issue by georgearun** [SpamScope/mail-parser#104]
I'm getting the following warning while reading **.eml** files "Email content 'calendar' not handled".

Code - `mailparser.parse_from_file("ujk9148.eml")`. This file contains calendar invites due to which warnings are displayed, due to which is affecting the performance of the code.
`warnings.filter("ignore")` also does not suppress this issue. Is there any way to disable this particular warning/issue.

**Comment by georgearun** [comment]
I am looking for a way to stop this warning from displaying in my code.

**Comment by kuleje** [comment]
I have a similar issue. I tried using [shutup](https://github.com/polvoazul/shutup) but with no success.

**Comment by calderwoodra** [comment]
If you don't care about the content in those parts, you can remove it with the following snippet:

```
eml_message = email.message_from_string(body)
    for part in eml_message.walk():
        if part.get_content_type() == 'text/calendar':
            part.set_payload('')
        elif part.get_content_type() == 'text/x-amp-html':
            part.set_payload('')
        elif part.get_content_type() == 'text/rfc-822':
            part.set_payload('')
    body = eml_message.as_string()
```

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
