### ISSUE TITLE
Mime Header Decoding (RFC 2047) does not correctly resolve in case the display name contains an encoded comma

### ISSUE THREAD

**Issue by Fabma** [SpamScope/mail-parser#105]
**Describe the bug**
The Mime Header Decoding (RFC 2047) does not correctly resolve in case the display name contains an encoded comma.
The entire mailbox-list is decoded _before_ separated into different mailboxes.

**To Reproduce**
The mail with header
`From: =?ISO-8859-1?Q?Moore=2C_Keith?= <moore@cs.utk.edu>`
is parsed to 
`mail._from == [('', 'Moore'), ('Keith', 'moore@cs.utk.edu')]`
It appears that the header is first decoded to `Moore, Keith <moore@cs.utk.edu>` before getting the individual addresses.

**Expected behavior**
Correct would be
`mail._from == [('Moore, Keith', 'moore@cs.utk.edu')]`

**Raw mail**
```
Delivered-To: bruce@untroubled.org
Received: (fqmail 26559 invoked from network); 21 Aug 2016 10:49:40 -0000
Reply-To: =?ISO-8859-1?Q?Moore=2C_Keith?= <moore@cs.utk.edu>
From: =?ISO-8859-1?Q?Moore=2C_Keith?= <moore@cs.utk.edu>
Subject: PI
Date: Fri, 19 Aug 2016 15:33:29 +0100
MIME-Version: 1.0
```

**Environment:**
 - mail-parser==3.15.0

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
