### ISSUE TITLE
from_ attribute contains two tuples for one sender

### ISSUE THREAD

**Issue by sgeulette** [SpamScope/mail-parser#107]
**Describe the bug**
When headers['From'] = 'Adam, Valérie \<valerie.adam@xxx.be\>' , the produced from_ attribute contains [('', 'Adam'), ('Valérie', 'valerie.adam@xxx.be')]
This is a mail sent by office365

**To Reproduce**
1. `import mailparser`
2. `mail = mailparser.parse_from_file(f)`
3. print(mail.from_)

**Expected behavior**
from_ value must be  [('Adam, Valérie', 'valerie.adam@xxx.be')]

**Raw mail**
`'Subject: test\nFrom: Adam, Valérie <adam.valerie@xxx.be>\nTo: yyy@xxx.be\nContent-Type: text/plain; charset="utf-8"\nContent-Transfer-Encoding: 7bit\nMIME-Version: 1.0\n\nmore\n'`

**Environment:**
 - OS: Linux
 - Docker: no
 - mail-parser version: 3.15.0

**Additional context**
nothing else

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
