### ISSUE TITLE
Is this able to parse latest reply?

### ISSUE THREAD

**Issue by c1am** [SpamScope/mail-parser#110]
Is mail-parser able to parse out the latest reply in an email thread?

**Comment by alfonsrv** [comment]
You can use either one of the following two libraries to extract the latest reply:

* https://github.com/zapier/email-reply-parser
* https://github.com/alfonsrv/mailparser-reply

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
