### ISSUE TITLE
Only parses Undelivered message for emails with bounced emails

### ISSUE THREAD

**Issue by abbykrishnan** [SpamScope/mail-parser#112]
**Describe the bug**
I have a raw email file in which one of the emails bounced. I would assume that I could parse both the 1) `Content-Description: Undelivered Message` email, as well as 2) the original email that had the bounced email, as there are valid addresses in that message. 

**To Reproduce**
1. `import mailparser`
2. `mail = mailparser.parse_from_bytes(f)`
3. `mailparsed_email.to` only contains the return email back to sender 

5. See error

**Expected behavior**

**Raw mail**
Raw email [gist](https://gist.github.com/abbykrishnan/f364865c7b0cbb957f4cc9c3b08114bc)

**Environment:**
 - OS: no
 - Docker: no
 - mail-parser version [e.g. 3.15.0]

**Additional context**
If there's another place that I need to be referencing to get information about both emails (or parse them into 2), please let me know!

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
