### ISSUE TITLE
Extracting mail signature

### ISSUE THREAD

**Issue by Qudirah** [SpamScope/mail-parser#114]
I am working on a project where I am extracting different parts of mail and the mail parser has been useful. I am quite shocked that this library cannot extract a signature. Is that in scope or can I suggest a method to work on that?

**Comment by woheme-c** [comment]
Hi Qudirah, I am also working on extracting the signature. Till now, I dont think a parser can handle that. I made some tests with machine learning nlp techniques. it seams to work. maybe that helps.

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
