### ISSUE TITLE
Publish the latest changes

### ISSUE THREAD

**Issue by evenicoulddoit** [SpamScope/mail-parser#119]
https://github.com/SpamScope/mail-parser/commit/7649ee8040c93dd6f832049adcc048d237b249da addressed a bug in the regex which causes errors when the mail ID ends in `-by`. Unfortunately this fix was never included in a build published on PyPI, so we're unable to benefit from it. Are you able to push out a new patch build so that we might benefit from it?

Thanks!

**Comment by fedelemantuano** [comment]
Can you check the last version?

**Comment by evenicoulddoit** [comment]
Amazing, thank you!
