### ISSUE TITLE
return in finally swallows exceptions

### ISSUE THREAD

**Issue by iritkatriel** [SpamScope/mail-parser#124]
In the following places:
https://github.com/SpamScope/mail-parser/blob/77fe01518628430c743b3c1e1649db625cd48114/src/mailparser/mailparser.py#L650
https://github.com/SpamScope/mail-parser/blob/77fe01518628430c743b3c1e1649db625cd48114/src/mailparser/mailparser.py#L663
there is a `return` statement in a `finally` block, which would swallow any in-flight exception.

This means that if an unhandled exception (including a `BaseException` such as `KeyboardInterrupt`) is raised from the `try` body, it will not propagate on as expected.

If the intention is to suppress all exceptions, I would propose to make this clear by using "except BaseException".

See also https://docs.python.org/3/tutorial/errors.html#defining-clean-up-actions.

**Comment by fedelemantuano** [comment]
Thanks for your contribution.
Fixed in PR #125
