### ISSUE TITLE
Create an official, Automated Build image on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [SpamScope/mail-parser#15]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags from git tags & branches (thus allowing to test ```:develop``` right away, [as shown](https://hub.docker.com/r/pataquets/mail-parser-src/builds/)).
Also, documentation could easily include a canonical `docker run` statement to quickly try the tool with just a single command.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags.
Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons. Docker search command clearly displays AB when listing images.

Just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by fedelemantuano** [comment]
I will do like in [SpamScope](https://github.com/SpamScope/spamscope/blob/develop/.travis.yml#L19). Travis will build and push images for me [here](https://hub.docker.com/r/fmantuano/mail-parser/)

**Comment by pataquets** [comment]
I completely understand your preference on using Travis because it's more convenient for the current workflow (I'm not too familiar with it as of now).
However, that approach has the drawback of not being tagged as an AB on all Docker UIs (web and cli). Verifiability is desirable for some. Added to that, both options are complementary, and an AB on each commit/branch & tag would enable wider testing and convenience to run a specific version.
How does that sound to you?

I also plan to port the tests as run on Travis into the Dockerfile, for running them on each hack/test cycle, but not sure about the convenience, especially if they're too long/heavy. What do you recommend? Which ones would be a good balance between speed/coverage?

**Comment by fedelemantuano** [comment]
I solved this issue with [this commit](https://github.com/SpamScope/mail-parser/commit/4ea4ff4433b8f4bd004681cd457475dc053b73e4).
