### ISSUE TITLE
Deal with 'cc' and 'bcc' as multi-recipient address email fields as done on 'to'

### ISSUE THREAD

**Issue by pataquets** [SpamScope/mail-parser#17]
This issue tracks followup to #16 and serves as discussion.
The 'bcc' field might appear is some cases, such as email proxies like [emailrelay](http://emailrelay.sourceforge.net/).

**Comment by fedelemantuano** [comment]
Solved with [this commit](https://github.com/SpamScope/mail-parser/commit/63df3a2e4096c89875805456d3909516da59b283).
