### ISSUE TITLE
Suggestion print only mail headers 

### ISSUE THREAD

**Issue by Maijin** [SpamScope/mail-parser#22]
Currently you can print all mail headers, but some of them can already be retrieved for example mail.retrieved get only the retrieved header, From, To etc.

Suggestion to add a command that print only the mail headers remaining (not available from the other command)

**Comment by fedelemantuano** [comment]
Hi @Maijin,

can you explain me what you want with an example?

Use this [gist](https://gist.githubusercontent.com/fedelemantuano/5dd702004c25a46b2bd60de21e67458e/raw/3fdff560c2c6078c416b959ca74567ddcb5470d6/1471832668.1377_3.ivanova.orig) for you example.

```
$ curl -s https://gist.githubusercontent.com/fedelemantuano/5dd702004c25a46b2bd60de21e67458e/raw/3fdff560c2c6078c416b959ca74567ddcb5470d6/1471832668.1377_3.ivanova.orig | mailparser -k -r

{
  "Received": "from host86-187-174-57.range86-187.btcentralplus.com ([86.187.174.57]:45321 helo=User)\n\tby localhost.localdomain.com with esmtpa (Exim 4.87)\n\t(envelope-from <anabelgonzalo@fanox.com>)\n\tid 1bakrE-000291-LF; Fri, 19 Aug 2016 20:34:52 +0600",
  "Delivered-To": "bruce@untroubled.org",
  "From": "\"Anabel Gonzalo\"<anabelgonzalo@fanox.com>",
  "X-Authenticated-Sender": "localhost.localdomain.com: quazi.limon@revesoft.com",
  "X-AntiAbuse": "Sender Address Domain - fanox.com",
  "X-Priority": "3",
  "X-MimeOLE": "Produced By Microsoft MimeOLE V6.00.2600.0000",
  "X-Get-Message-Sender-Via": "localhost.localdomain.com: authenticated_id: quazi.limon@revesoft.com",
  "X-MSMail-Priority": "Normal",
  "Date": "Fri, 19 Aug 2016 15:33:29 +0100",
  "Reply-To": "<anabelgonzalo@fanox.com>",
  "MIME-Version": "1.0",
  "Content-Type": "multipart/mixed;\n\tboundary=\"----=_NextPart_000_0121_01C2A9A6.50D724E0\"",
  "X-Mailer": "Microsoft Outlook Express 6.00.2600.0000",
  "Subject": "PI"
}
```

**Comment by Maijin** [comment]
"Received," "Delivered-To", "From", "Reply-To", "Subject" are all fields that can already been retrieved by .from, .to, retrieved etc. 

I was looking for a command to get the dict of headers that are remaining without the one that can be get by those command.

But now I see the JSON maybe I can just use the json dict and remove the field myself though let me close that.
