### ISSUE TITLE
Question: Can mail-parser recover nested messages?

### ISSUE THREAD

**Issue by silentsnooc** [SpamScope/mail-parser#25]
I hope it's okay if I'm asking this here.

A lot of data sets (e.g. Enron) contain only plain text messages or no explicit information whether an email has been forwarded or replied. 

In order to reconstruct this information I was thinking about trying to recover nested messages e.g. (just an example)

```
Message-ID: <10792109.1075856435465.JavaMail.evans@thyme>
Date: Fri, 4 May 2001 10:39:00 -0700 (PDT)
From: vince.kaminski@enron.com
To: loleary@riskwaters.com
Subject: Lunch

Hey, when do you want to have lunch today?
```

and 

```
Message-ID: <12168444.1075856436014.JavaMail.evans@thyme>
From: loleary@riskwaters.com
To: vince.kaminski@enron.com
Subject: Re: Lunch

How about 12:30 pm ?

 -----Original Message-----
vince.kaminski@enron.com
05/04/2001 10:39 PM
To: loleary@riskwaters.com
Subject: Lunch

Hey, when do you want to have lunch today?
```

Where the first message "*Hey, when do you..*" would be labelled for example as `HAS_ANSWERED`.

Can this be done with `mail-parser` or are there any libraries which could do something like that?

**Comment by fedelemantuano** [comment]
This is a right question. For now you have:

```
$ mailparser -f /tmp/mail.txt -j

{
  "body": "How about 12:30 pm ?\n\n -----Original Message-----\nvince.kaminski@enron.com\n05/04/2001 10:39 PM\nTo: loleary@riskwaters.com\nSubject: Lunch\n\nHey, when do you want to have lunch today?",
  "to": [
    [
      "",
      "vince.kaminski@enron.com"
    ]
  ],
  "has_defects": false,
  "from": [
    [
      "",
      "loleary@riskwaters.com"
    ]
  ],
  "subject": "Re: Lunch"
}
```
All bodies of messages are in body field. mail-parser doesn't get on this information in custom field because I should think to all nested messages.
Mailparser doesn't use plugin, but I can develop this feature in it.

The _reply-to_ and _forward_ mails have custom header that I can use for this scope.

Can you have some suggestion?
Can you have a raw email that I can use as test?

**Comment by fedelemantuano** [comment]
If you have any suggestions, please open a new issue o PR.
