### ISSUE TITLE
Decoding of payload of attachment

### ISSUE THREAD

**Issue by ad-m** [SpamScope/mail-parser#27]
Hello,

I am have following code in my project:

```python

decoder_map = {'base64': lambda payload: base64.b64decode(payload),
               '': lambda payload: payload.encode('utf-8'),
               '7bit': lambda payload: payload.encode('utf-8'),
               'quoted-printable': lambda payload: quopri.decodestring(payload)}
for msg_id in data[0].decode('utf-8').split():
    result_fetch, data = client.fetch(msg_id, "(RFC822)")

    if result_fetch != 'OK':
        raise Exception("Fetch failed!")

    raw_mail = data[0][1]
    mail = mailparser.parse_from_bytes(raw_mail)
    for attachment in mail.attachments:
        if attachment['content_transfer_encoding'] not in decoder_map:
            msg = "Unsupported Content-Transfer Encoding ({}) in msg {}.".format(attachment['content_transfer_encoding'], msg_id)
            raise RuntimeError(msg)

        decoder = decoder_map[attachment['content_transfer_encoding']]
        try:
            fp, fname = find_filename(attachment['filename'], args.attachment_dir)
            fp.write(decoder(attachment['payload']))
        except binascii.Error as e:
            print("Unable to parse attachment '{}'".format(attachment['filename']))
        finally:
            fp.close()
```

I think that this is not a fully-handled case of use. I had to introduce quite a lot of logic to save attachments that can be coded in a variety of ways.

**Comment by fedelemantuano** [comment]
I understood but `mail-parser` is a parser. If you want store sample on filesystem you should manage possible issues.
I can't introduce extra logic.

**Comment by ad-m** [comment]
In my opinion, proper decoding of binarny attachments to a binary form native to Python is a part of parsing. In my opinion, the logic around `` `decoder_map`` is an element of the project. This is in the scope of the project as much as the date parsing that is present today. Of course, saving attachments is out of the project. Parsing attachments of mail to the native binary form does not require writing them to the disk.

**Comment by fedelemantuano** [comment]
Hi @ad-m,

in `mail-parser` results there is a `binary` flag. If it's `true` the sample is a binary, it's `false` is not binary.
If you read this [part of code](https://github.com/SpamScope/mail-parser/blob/develop/mailparser/mailparser.py#L335) you can see:

```
...
charset = p.get_content_charset('utf-8') # get the charset
....

            if filename:
                    binary = False
                    mail_content_type = ported_string(p.get_content_type())
                    transfer_encoding = ported_string(
                        p.get('content-transfer-encoding', '')).lower()

                    if transfer_encoding == "base64" or \
                            (transfer_encoding == "quoted-printable" and
                             "application" in mail_content_type):
                        payload = p.get_payload(decode=False)
                        binary = True
                    else:
                        payload = ported_string(
                            p.get_payload(decode=True), encoding=charset)
```
`mail-parser` gives you the correct payload, so you should do:

```
            if binary:
                with open(sample, "wb") as f:
                    f.write(payload.decode("base64"))
            else:
                with open(sample, "w") as f:
                    f.write(payload.encode("utf-8"))
```

That's it

**Comment by louis-red** [comment]
@fedelemantuano I stand on @ad-m's side on this one. 
Maybe you think the attachments decoding is a trivial task, but it is one that will be done by each user that is interested in the attachments, and they will have to implement that little bit of logic in their code after having looked at that issue.

Maybe what is best on the user side is a common binary format for the payload, and additional logic should be kept (and possibly simplified) on the module side ?

**Comment by fedelemantuano** [comment]
I added the `store attachments` function in `mail-parser` command line:

```
$ mailparser -f my_mail -sa -ap /tmp/attachments
```
