### ISSUE TITLE
to_json returns []

### ISSUE THREAD

**Issue by ryanharnwell** [SpamScope/mail-parser#34]
`import mailparser`
`mail = mailparser.parse_from_file('samples/eml_file')`
`print(mail.to_json)`

returns []

(other functions like mail.body work as expected)

**Comment by fedelemantuano** [comment]
Is this an Outlook message? If yes, you should use:

```
import mailparser
mail = mailparser.parse_from_file_msg('samples/eml_file')
print(mail.to_json)
```

Can you share your test mail?

**Comment by ryanharnwell** [comment]
Return-Path: <aaaaaa@bbbbbb.com>
Received: from mail-wr0-f172.google.com (mail-wr0-f172.google.com [209.85.128.172])
 by inbound-smtp.eu-west-1.amazonaws.com with SMTP id 02e829lfqskt2sesvioeeabf86gfgqo8bgsah5g1
 for aedwaedf@projects.ccccc.com;
 Wed, 20 Jun 2018 10:05:46 +0000 (UTC)
Received-SPF: none (spfCheck: 209.85.128.172 is neither permitted nor denied by domain of bbbbbb.com) client-ip=209.85.128.172; envelope-from=aaaaaa@bbbbbb.com; helo=mail-wr0-f172.google.com;
Authentication-Results: amazonses.com;
 spf=none (spfCheck: 209.85.128.172 is neither permitted nor denied by domain of bbbbbb.com) client-ip=209.85.128.172; envelope-from=aaaaaa@bbbbbb.com; helo=mail-wr0-f172.google.com;
 dkim=pass header.i=@hhhhhh-com-au.20150623.gappssmtp.com;
X-SES-RECEIPT: AEFBQUFBQUFBQUFGV1hGdkh6NmFZODJ4aVVUcFRKZStsNGdSWjhMQ0lUNlJhL3lML2diK0NZZms1NlJsOFlXUGJMK1hhNnFqYWR6UE5iVVhPSkU4bkk4SmVnWTU0SDNrY25YRnVuRW92NkZZeEx6VE9UWkpwQWkwL3hSejhYcFJOd2NyVTFrWTNpd1cydmN4anJQQXc0TXAvWjcyaGExVXV0dE5jTFhYVzFyVVlvS3NOblpOekdHVkpXYWxuTG9OeGdvUE1BNVQ1ZWt6OXBCVVR2UG9wV1dPRTI0NkdwdU9seHZSbmM4bDkrZm5IQXZHM0FVNmtjMHFOcm5LYzdHRW84cmRFQjdMM2RlSWw0REREMXpSQXZhZnJ4M1pnRTQ1a0RXam54SWJNdGNLT2NFc0NGU3FOclE9PQ==
X-SES-DKIM-SIGNATURE: a=rsa-sha256; q=dns/txt; b=TKehW9kn7CXYa43M1LIdlsC1yVJzFfHGs8HA2lp80HQEXaw4+P+xcOqcFkCzWJrWaGuKZiOajgU5WY2fPGHNmS/X//LKHFS3JO19PHTReQjDzdv07zLV58xLI+Xj9bP23bkIxpUE1kJ+Qfayp0kBGHHBRcMldaX+mkiteNd+k0Q=; c=relaxed/simple; s=uku4taia5b5tsbglxyj6zym32efj7xqv; d=amazonses.com; t=1529489148; v=1; bh=JoKNYvUlb3NM1F+KEpK+cjfISx+ang3D7x892kKNtoM=; h=From:To:Cc:Bcc:Subject:Date:Message-ID:MIME-Version:Content-Type:X-SES-RECEIPT;
Received: by mail-wr0-f172.google.com with SMTP id h10-v6so2633183wrq.8
        for <aedwaedf@projects.ccccc.com>; Wed, 20 Jun 2018 03:05:46 -0700 (PDT)
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=hhhhhh-com-au.20150623.gappssmtp.com; s=20150623;
        h=mime-version:from:date:message-id:subject:to;
        bh=JoKNYvUlb3NM1F+KEpK+cjfISx+ang3D7x892kKNtoM=;
        b=AGhUMuqlAI5Jn/6mpDF988E570Xsw/3jdIScm3RaGRo3N+e9aUHKngLqBtBByQGJlt
         4dEOZg/jz0uST+Xdl3MKvmr1F9wIRtertihncoXjw9R5vA7Q/iOHhw+wW7hozrD1rL1r
         fID75MfB1WU1kZV9iw51Gc9DYdB52AvZfyWYQ6r+cvZjNCxjnH2kO7lOwyyXBDFimgjx
         4YD95FRkMAis+6K1vg3wCd9jHVqrY9ShRQz3QIqPraffUx1mGCx4I523cfSpbtPfY3H+
         2PFLmG0qIDJVKlSknSbvefNWBZ8/E9/5+JTfGNt9VhRwXgt+dr6y8A/soEH7QEh0MJLi
         xw3w==
X-Google-DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed;
        d=1e100.net; s=20161025;
        h=x-gm-message-state:mime-version:from:date:message-id:subject:to;
        bh=JoKNYvUlb3NM1F+KEpK+cjfISx+ang3D7x892kKNtoM=;
        b=V9+iYHPJyL4qz3L9DrH1Y5dayREAk4DoG1Q/ldZMAnvB0isWEU6jjxI3udJJCb/I3Y
         L78vgOT6UKW3rPbebcIAvTPPtKac8qO00eNgJnZRNb8IEIf6cp30EDDYnbQYpjcHu1mP
         yPpfh5zN7zOmoj2qG9vyaODCvhAIjkK/HHieAhPVV4yN6Bimg2hoJK7DihR8SQAD2bHn
         irYOlhbarFdnyO6QHBnIPbKC8mAxL8PNYVKYxeit9MhjUxPDBnNNOukmC9EtUDgF01h1
         nOZSJuyYi/rJoJ5mufii2SkZbIOOjYKzKFnFzIAK7n3hAF0R3wO1cWhxJ3OZtwi4LBuU
         fHFQ==
X-Gm-Message-State: APt69E1PqoILK41ECD5inr9hv2FRmYmPVubLLFYmLs5XbzSEHnKraRWO
tGFXRwqP7Wvm8MrAao2REWsS3UI5GOYLtjg8pyOFfA==
X-Google-Smtp-Source: ADUXVKKzytY+z912JXem99gngjFxixQ93ZRZCjwoCFHPvZiLEiR6VHfTexbsWUqN6BxMo3e5Q7BRy5rV8TtYLpurDMg=
X-Received: by 2002:adf:a949:: with SMTP id u67-v6mr16518978wrc.71.1529489145406;
 Wed, 20 Jun 2018 03:05:45 -0700 (PDT)
MIME-Version: 1.0
Received: by 2002:a1c:d414:0:0:0:0:0 with HTTP; Wed, 20 Jun 2018 03:05:44
 -0700 (PDT)
From: aaaaaa Harnwell <rh@hhhhhh.com.au>
Date: Wed, 20 Jun 2018 20:05:44 +1000
Message-ID: <CA+Cz=thSc9g2SVLmCCkbaOkePR7egq7v_SC6o22URje1tEDNKg@mail.gmail.com>
Subject: test
To: aedwaedf@projects.ccccc.com
Content-Type: multipart/alternative; boundary="000000000000333b83056f0ff14b"

--000000000000333b83056f0ff14b
Content-Type: text/plain; charset="UTF-8"

body text

--000000000000333b83056f0ff14b
Content-Type: text/html; charset="UTF-8"
Content-Transfer-Encoding: quoted-printable

<h1>body text</h1>

--000000000000333b83056f0ff14b--

**Comment by ryanharnwell** [comment]
I think it's a regular eml file, its been received from Amazon ses
