### ISSUE TITLE
mail.date does not return timezone information

### ISSUE THREAD

**Issue by Sunny-Engineer** [SpamScope/mail-parser#35]
The routine should return the dates with timezone offset information.  Prefered would be iso 8601 ex: 2013-10-29T09:38:41.341Z

**Comment by fedelemantuano** [comment]
This date is in `UTC`. In the _README_:

```
mail.date: datetime object in UTC
```

**Comment by Sunny-Engineer** [comment]
I understand that the system saves the date in UTC.  However, by doing so and not saving the original timezone, there is no way to determine what the original timezone was of the senders email.   We want to know what timezone the user sent from so that we can reply during normal business hours.

**Comment by fedelemantuano** [comment]
Problem solved with [this commit](https://github.com/SpamScope/mail-parser/commit/e26f8f57210fc9a923aa207f8ce4f9514d64c6e2).

Added `timezone` property and timezone in main json.

**Comment by Sunny-Engineer** [comment]
Our testing shows that this works as desired.   We have not tested all timezones, but it appears to do what was needed.  Thanks!
