### ISSUE TITLE
PST files

### ISSUE THREAD

**Issue by naarkhoo** [SpamScope/mail-parser#40]
I wonder if there is a possibility to add functionalities to read PST (outlook) format ? Probably this could be relevant https://github.com/libyal/libpff

**Comment by fedelemantuano** [comment]
Hi @naarkhoo,
did you try this option (`-o, --outlook         Analyze Outlook msg (default: False)`)?
mail-parser can analyze outlook mails.

**Comment by fedelemantuano** [comment]
To use outlook parser, you shoud install `libemail-outlook-message-perl`. I don't know if this package exists in Windows, but you can use the docker image https://hub.docker.com/r/fmantuano/spamscope-mail-parser/.
In this image there are all requirements.

**Comment by fedelemantuano** [comment]
If you have others questions, you can open a new issue.
