### ISSUE TITLE
Parsing of receiveds doesn't support via or id

### ISSUE THREAD

**Issue by dfeinzeig** [SpamScope/mail-parser#42]
for example:

```
Received: from XXX.namprd06.prod.outlook.com (2603:10b6:207:3d::31) by XXX.namprd06.prod.outlook.com with HTTPS id 12345 via XXX.NAMPRD02.PROD.OUTLOOK.COM; Mon, 1 Oct 2018 09:49:22 +0000
```

**Comment by fedelemantuano** [comment]
Hi @dfeinzeig @Maijin,

the received header depends from client and there isn't standard, so in `mail-parser` I'm using regex.
Can you give me a mail example to add to unittest?

**Comment by dfeinzeig** [comment]
hi @fedelemantuano ,

the above example i provided is a copy and paste (also note the ipv6). you can add that to any existing test email's set of receiveds. i was looking at your regexes to add in the id and via, but couldn't quite figure out which each block of regexes was for. i'm glad to help with this, but would appreciate any more details you can provide on how you've structured your regexes.

id seems to optionally follow with

via seems to optionally follow for

though, to your point, the RFC doesn't seem to specify order. i was wondering if it makes sense to change the regexes you have to something like

from [by|with|id|for|via|envelope-from]
by [from|with|id|for|via|envelope-from]
...

to allow for any order of clauses

**Comment by fedelemantuano** [comment]
Hi @dfeinzeig 
mailparser uses some regexps to parse receiveds (in `const.py`).
Receiveds are very irregulars and doesn't exist a regex that can parse all cases.

I tested your case with [mxtoolbox.com](https://mxtoolbox.com/Public/Tools/EmailHeaders.aspx) and doesn't parse those parts of header.

mailparse does this:

```
  {
    "from": "XXX.namprd06.prod.outlook.com 2603:10b6:207:3d::31",
    "delay": 2812952.0,
    "date_utc": "2018-10-01T09:49:22",
    "hop": 3,
    "date": "Mon, 1 Oct 2018 09:49:22 +0000",
    "with": "HTTPS id 12345 via XXX.NAMPRD02.PROD.OUTLOOK.COM",
    "by": "XXX.namprd06.prod.outlook.com"
  }
``` 
I don't want change this regex, can become unstable.
But if you want, you can send me a PR.

**Comment by dfeinzeig** [comment]
@fedelemantuano , i'm thinking something along the lines of

`import re
import exceptions
RECEIVED_PATTERNS = [
    r'(?:from\s+(?P<from>.+?)(?:\s+by|\s+with|\s+id|\s+for|\s+via|;))',
    r'(?:by\s+(?P<by>.+?)(?:\s+from|\s+with|\s+id|\s+for|\s+via|;))',
    r'(?:with\s+(?P<with>.+?)(?:\s+from|\s+by|\s+id|\s+for|\s+via|;))',
    r'(?:id\s+(?P<id>.+?)(?:\s+from|\s+by|\s+with|\s+for|\s+via|;))',
    r'(?:for\s+(?P<for>.+?)(?:\s+from|\s+by|\s+with|\s+id|\s+via|;))',
    r'(?:via\s+(?P<via>.+?)(?:\s+from|\s+by|\s+id|\s+for|\s+with|;))',
    r';\s*(?P<datetime>.*)'
]
RECEIVED_PATTERNS_COMPILED = [re.compile(pattern, re.IGNORECASE|re.DOTALL) for pattern in RECEIVED_PATTERNS]
def parse_received(received):
    values_by_clause = {}
    for pattern in RECEIVED_PATTERNS_COMPILED:
        matches = [match for match in pattern.finditer(received)]
        if len(matches) == 0:
            # no matches for this clause, but it's ok! keep going!
            continue
        elif len(matches) > 1:
            # uh, can't have more than one of each clause in a received.
            # so either there's more than one or the current regex is wrong
            raise exceptions.ValueError("More than one match found for %s in %s" % (pattern.pattern, received))
        else:
            # otherwise we have one matching clause!
            match = matches[0].groupdict()
            values_by_clause[match.keys()[0]] = match.values()[0]
    return values_by_clause`

I realize that's incomplete so far, but seems like it'll be easier to maintain the regexes.

**Comment by fedelemantuano** [comment]
Ok,

try to send me a PR, so I can analyze better your code.

**Comment by askariblue** [comment]
Was this ever resolved?

**Comment by fedelemantuano** [comment]
No, I didn't have time for this issue. But I will watch it.
