### ISSUE TITLE
ipaddress requirements in Python 3.3+

### ISSUE THREAD

**Issue by slavkoja** [SpamScope/mail-parser#50]
I am building own Debian's package, then mailparser is not installed via pip and i am using it with Python 3.7.

In the requirements.txt is a ipaddress module, which is part of Python3 standard lib from 3.3 version. I didn't inspect the source in depth, but it seems to work, when i use mailparser module from a script, but when i try to run it as command, it complains about missing distribution under python 3.7:
```python
pkg_resources.DistributionNotFound: The 'ipaddress' distribution was not found and is required by the application
```
As i can see in ipaddress package description, it is port of built-in module to older versions of Python without it, then it is (have to be) useless in Python 3.3+. Please, consider make this requirement conditional, depending on used Python version.

**Comment by fedelemantuano** [comment]
Please use the template issue to explain your issue, I can't understand without more information.
