### ISSUE TITLE
How should I make this work for .MSG files ?

### ISSUE THREAD

**Issue by ameyn21** [SpamScope/mail-parser#54]
I have used mailparser for extracting attachments from .EML files. But I am not able to use it for .MSG files. I read about the installation of 'libemail-outlook-message-perl' for parsing .MSG files. But I am not sure how to install it for windows.

**Comment by fedelemantuano** [comment]
I suggest you to use Docker images: https://microbadger.com/images/fmantuano/spamscope-mail-parser.
For Windows I don't have steps to install that library.
