### ISSUE TITLE
write_sample does not create directory structure included in $filename

### ISSUE THREAD

**Issue by bf** [SpamScope/mail-parser#56]
**Describe the bug**
When an attachments has a filename containing `/`, then `write_sample()` function call fails with `Error: No such file or directory: '/tmp/foo/bar/attachment.png'`

**To Reproduce**
1. `mailparser -f foo -sa -ad /tmp` on email with attachment that has a slash in the file name
2. observe error

**Expected behavior**
`write_sample()` should create subdirectories not only for attachment output dir specified in `-ap`, but also for the directory structure included in the attachment filename

**Raw mail**

**Environment:**
 - OS: linux
 - Docker: no
 - mail-parser version 3.9.3

**Comment by fedelemantuano** [comment]
See #PR57
