### ISSUE TITLE
Is there a method for downloading attachments if using mail-parser as module in project?

### ISSUE THREAD

**Issue by crayon-chaos** [SpamScope/mail-parser#59]
Maybe I am missing something or is there nothing in the readme about retrieving the actual email attachments. 
There are methods for getting the attachment names but not the actual files? (mail.attachments)

Thanks in advance.

**Comment by crayon-chaos** [comment]
Implementation would look like mail.attachments.download(destination)

`def download(self, destination):
    for attachment in self.attachments:
         with open(attachment['filename'], "wb") as code:
            code.write(attachment['payload']`

**Comment by fedelemantuano** [comment]
Hi @crayon-chaos I can't understand. Do you want get only file names?
With the flag `-sa, --store-attachments` you can store the attachments on disk.

**Comment by fedelemantuano** [comment]
It's possible to add the store function in module or use your snippet.

**Comment by crayon-chaos** [comment]
Hey, thanks for picking up this thread.

I was referring to when importing mail-parser as a library -- there is no
obvious way to download attachments.
Tanks for resolving this.
