### ISSUE TITLE
New  release on pypi?

### ISSUE THREAD

**Issue by dice89** [SpamScope/mail-parser#60]
**Is your feature request related to a problem? Please describe.**
Can you update the release on pypi? Would help me a lot thx!

**Describe the solution you'd like**
A new release i.e. with the content-disposition header for attachments.

**Comment by fedelemantuano** [comment]
I will develop a new release in these days.

**Comment by fedelemantuano** [comment]
I released a new version of [mailparse](https://github.com/SpamScope/mail-parser/releases/tag/v3.10.0).
