### ISSUE TITLE
Error in timezone parsing

### ISSUE THREAD

**Issue by saeed-abdullah** [SpamScope/mail-parser#61]
**Describe the bug**

The timezone parsing only works for offsets with full hours. For example, parsing a date with +05:30 returns "+6", which is incorrect. This bug potentially impacts a number of significant regions (e.g., India with offset +05:30, Austalia — ACST with offset +09:30).

**To Reproduce**
```
from email.utils import parsedate_tz
import mailparser
d = "Mon, 11 Dec 2017 15:27:44 +0530"
print(parsedate_tz(d)[9]/3600)  # 5.5
print(mailparser.utils.convert_mail_date(d)[1])  # +6 -- should be 5.5
```

**Raw mail**
Raw mail is not necessary to produce the error

**Environment:**
 - OS: [macOS Mojave (10.14)]
 - Docker: no
 - mail-parser version 3.9.3

**Additional context**
The bug results from using 0 decimal precision while formatting the [timezone string](https://github.com/SpamScope/mail-parser/blob/c90cb1cd72fcf986fa013acbbc1277b7b6fa2e84/mailparser/utils.py#L348). I recommend using 2 decimal precision to address this bug (please see the [patch](https://gist.github.com/saeed-abdullah/7b45dcb4de61fa55411399ba542134ce)). Or, we can keep the offset as returned by `email.utils.parsedate_tz` (in seconds).

**Comment by fedelemantuano** [comment]
Hi @saeed-abdullah thank for your contribution.
The time conversion was corrected but the timezone no. With this fix now both are correct.
