### ISSUE TITLE
Custom Header only takes first occurence

### ISSUE THREAD

**Issue by Hopyoprop** [SpamScope/mail-parser#62]
**Utilisation of Custom headers**
When utilising calling custom headers from a mailparser object, the return value is only 1 and does not return a list when there is more than one of that email header. EG: "Received-SPF".

**To Reproduce**
Have a .MSG file with email headers with more than one of the same attribute such as "Received-SPF" and when calling mail.Received_SPF only gives you the first occurrence instead of a list with all of them

**Environment**
Python 3.8.0 using latest release of Pypi3 Mailparser.

**Comment by fedelemantuano** [comment]
Thanks for this issue. The bug is solved. The next release will be the fix.
