### ISSUE TITLE
six is fixed at v1.13.0

### ISSUE THREAD

**Issue by sjcurtinibm** [SpamScope/mail-parser#65]
**Describe the bug**
* six have released version 1.14.0
* requirements.txt file has six fixed at v1.13.0 https://github.com/SpamScope/mail-parser/blob/develop/requirements.txt#L3
* This is giving dependency issues as some libraries download the latest, but this is fixed to 1.13.0
* We could bump it or change sign to >= ?

**To Reproduce**
* Have 2 python modules that use six
* One is dependant >= 1.13.0
* One is == 1.13.0

**Expected behavior**
Both Python Modules install fine

**Actual behavior**
We get a dependency confilct :(

**Environment:**
 - any

**Comment by fedelemantuano** [comment]
Hi @sjcurtinibm,
this is a problem on your system and not of mail-parser. You should use [virtualenv](https://virtualenv.pypa.io/en/latest/).
I can upgrade the library, but the best practice is the virtualenv.

**Comment by seanthegeek** [comment]
@fedelemantuano  `six` is updated often, and other packages have different version requirements. Setting a static version causes conflicts with  `setup.py` requirements in other modules that use slightly newer or older versions of `six`, even if you use `pip` in a virtualenv. I agree with @sjcurtinibm , `six` should really be set at `six>=1.12.0` to be more friendly to other dependencies in the same virtualenv.
