### ISSUE TITLE
 HTML body regression in mail-parser 3.12.0 

### ISSUE THREAD

**Issue by seanthegeek** [SpamScope/mail-parser#67]
**Describe the bug**
HTML bodies (raw or base64-encoded) without a email `boundary` are treated as a binary attachment instead of HTML body content. This bug was not present in 3.11.0.

**To Reproduce**
1. `import mailparser`
2. `mail = mailparser.parse_from_file(f)`
3. See error

**Expected behavior**
The HTML body should be parsed as the message body

**Raw mail**
Samples **Warning - includes phishing emails**: [samples.zip](https://github.com/SpamScope/mail-parser/files/4531003/samples.zip) Password: `infected`.

**Environment:**
 - OS: Linux
 - Docker: No
 - mail-parser version 3.12.0

**Comment by seanthegeek** [comment]
Hi @fedelemantuano,

I did more testing, and the regression occurs when HTML bodies (both raw or base64-encoded) are used without any `Message-Boundary`.

```rfc822
Content-Type: text/html; charset="us-ascii"
Content-ID: <C7C2F6D09AFDF04DB9FA01B76CA64E27@cardinalhealth.com>
MIME-Version: 1.0

<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=us-ascii">
</head>
<body>
Example
</body>
</html>
```
I've uploaded samples with identifying information removed.

Samples *Warning - includes phishing emails*: [samples.zip](https://github.com/SpamScope/mail-parser/files/4531003/samples.zip) Password: infected.

**Comment by fedelemantuano** [comment]
Maybe the problem started from PR #64. I will fix it.

**Comment by fedelemantuano** [comment]
I can't understand. I tested your emails but all HTML are in body.
Can you give me more details?

```
 $ mailparser --version
mailparser 3.12.0
 $ mailparser -f /mnt/testing/mailparser/samples/YourSmartSolve\ Account\ Has\ Been\ Created.eml -j 
{
  "thread-topic": "Your SmartSolve Account has been created.",
  "mime-version": "1.0",
  "subject": "Your SmartSolve Account has been created.",
  "date": "2017-08-28T11:11:23",
  "timezone": "-4.0",
  "content-type": "text/html; charset=\"us-ascii\"",
  "body": "<html>\n<head>\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=us-ascii\">\n</head>\n<body>\n<div>Dear renee meyers, your SmartSolve account has been created. Your username is redacted. Thank you for being a part of the Pilgrim Quality Solution SmartSolve family.\n</div>\n</body>\n</html>",
  "thread-index": "AQHTH+5juWxx1crEzUeTknVCEy3hUQ==",
  "has_defects": false
}
```

**Comment by seanthegeek** [comment]
@fedelemantuano Sorry I just now noticed your replies. I was wrong about the cause of the bug, so my attempts to simplify/redact the emails failed to reproduce the issue. You are exactly right. The issue was caused by PR #64.

Often messages will add a `Content-ID` header to an HTML body part of an email. mail-parser parser still parsed the body correctly, but PR #64 caused those email bodies to *also* be incorrectly be treated as an attachment. 

```email
--_000_450A05536D04B1AE5PQSSMTPGBLB03pilgrimaspcom_
Content-Type: text/html; charset="utf-8"
Content-ID: <705D55D15DB6CD4681934E1C11784FA1@namprd04.prod.outlook.com>
Content-Transfer-Encoding: base64
```

It looks like you already fixed this issue in the `develop` branch. Can you put out a release so I can update my downstream projects?

**Comment by Passimist** [comment]
I am having the same issue. If a HTML body part of an email has a Content-ID it is treated as an attachment.
Do you know, when the fix will be released?

**Comment by fedelemantuano** [comment]
I've just release version 3.13.0. This issue should be solved.

**Comment by Passimist** [comment]
@fedelemantuano Thank you for your work on this project! Would you mind telling me what you changed to fix this issue? I always suspected the problem to be around line 359-363 in the mailparser.py (This is where I changed to code for me locally to avoid html parts appearing as attachments.)
I was thinking:
Since it takes the ContentID if there is no filename and the check for "is attachment" is "if filename:" everything that has a contentid but no filename is treated as an attachment. But often html text has a contentid but no filename and is interpreted as attachment here. So I changed this to something like "if filename and not content-type == 'text/html" and not content-type == "text/plain" and content-disposition == attachment".
But my "fix" probably leads to attachments beeing wrongly interpreted as mailbody.

I would love to hear your opinion on this and to know how you fixed this issue in the new version.

**Comment by fedelemantuano** [comment]
@Passimist, I tested the email in this thread and I did't have any issue. Can you send me an email with this problem?
