### ISSUE TITLE
Email content 'rtf' not handled

### ISSUE THREAD

**Issue by Hopyoprop** [SpamScope/mail-parser#68]
With the latest version of Spamscope mailparser v3.12.0, there is a warning log that I see popping up when parsing MSG files. 

For each MSG file I parse I keep getting this Email content 'rtf' not handled log. I know its that I am not handling rtf of the maildata text but how can I avoid this warning log from appearing.

**Comment by fedelemantuano** [comment]
I need an example to test it. Please follow the issue template.

**Comment by seanthegeek** [comment]
The only time I've seen RTF in an email body is when Microsoft Outlook `.msg` files are converted to RFC822 format using something like `msgconvert`. The `.msg` unfortunately stores the body that was originally HTML as RTF. No other mail client/parser other than Outlook can read the RTF body from what I've seen, and instead falls back to the plain text body. The raw RTF content shows up under `text_not_managed`.

  Here's a sample


[RTF email bodies.zip](https://github.com/SpamScope/mail-parser/files/4531238/RTF.email.bodies.zip)

**Comment by seanthegeek** [comment]
@Hopyoprop As a workaround, if you attach a MSG file to a blank draft email, and then open the draft in Outlook webmail, you can download the attachment as a RFC822 .eml file with the HTML formatting intact :)

**Comment by Hopyoprop** [comment]
Hmm I'll give it a go Sean! But yeah sorry fedelemantuano, the mails for this case scenario I'm using are confidential information so won't be able to share them.

**Comment by fedelemantuano** [comment]
@Hopyoprop I know but can you send me the email with fake data?

**Comment by seanthegeek** [comment]
@fedelemantuano I provided samples here 

https://github.com/SpamScope/mail-parser/files/4531238/RTF.email.bodies.zip

**Comment by Rashe** [comment]
> . No other mail client/parser other than Outlook can read the RTF body from what I've seen

How other vendors deal with it then? I mean gmail, etc.

**Comment by fedelemantuano** [comment]
I solved this strange issue.
From documentation:

```
Content-Disposition takes one of two values, `inline' and `attachment'. 'Inline' indicates that the entity should be immediately displayed to the user, whereas `attachment' means that the user should take additional action to view the entity.
```

In this case we have:

```
Content-Type: application/rtf
Content-Transfer-Encoding: base64
Content-Disposition: inline
```

So this isn't a real attachment, but you can't read it with actual version (*v3.14.0*).
I opened the example mail with a mail client, and it puts `rtf` in attachments and give to it an `attachment` name.
So mailparser will thread it as attachments too and it will give a random name (a can have more attachments) with `rtf` extension.

I tested it and it works.
