### ISSUE TITLE
No matches found

### ISSUE THREAD

**Issue by scruggsc** [SpamScope/mail-parser#69]
**Describe the bug**
i get the message DEBUG: mailparser.utils: No matches found for (?:for\s+(?P<for>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+id|\s+via|;)) in by mail-io1-f43.google.com with SMTP id 32iod.6;^M Tue, 31 Mar 2020 18:16:56 -0700 PDT

**To Reproduce**
i'm not actually sure what causes this. i'm new to email standards etc; could you give me a brief rundown of whats going on here?

**Expected behavior**
i assume this is supposed to happen?

DEBUG: mailparser.utils: Found one match for [^\w](?:id\s+(?P<id>.+?)(?:\s*[(]?\
envelope-from|\s*[(]?envelope-sender|\s+from|\s+by|\s+with(?! cipher)|\s+for|\s\
+via|;)) in by mail-io1-f43.google.com with SMTP id c16so9479032iod.6;^M Tue, 3\
1 Mar 2020 18:16:56 -0700 PDT

**Raw mail**
using only the information above, is there a way to work backwards to the email? it takes hours to parse the amount of emails to get here and i don't believe it can be caught in a try/except

**Environment:**
 - OS: linux
 - Docker: no
 - mail-parser version [e.g. 3.6.0]

**Comment by fedelemantuano** [comment]
Hi @scruggsc,

there isn't a standard to parse received header, so I developed a regex to get the commons cases.
Without the mail I can't add a new regex, so I will close this issue.

**Comment by scruggsc** [comment]
> Hi @scruggsc,
> 
> there isn't a standard to parse received header, so I developed a regex to get the commons cases.
> Without the mail I can't add a new regex, so I will close this issue.

hey sorry about that; i was busy today and couldn't research how to print a raw email. how's this?

https://gist.github.com/scruggsc/c79db5df4ae1947f4a6535dc2a297627

**Comment by fedelemantuano** [comment]
I can't test without raw mail. So I should close this issue.
