### ISSUE TITLE
Attachment Payload Shouldn't be Trimmed

### ISSUE THREAD

**Issue by LiamMahoney** [SpamScope/mail-parser#70]
**Describe the bug**

I'm trying to generate MD5 hashes of attachments found in email files. I'm using that MD5 in a tool like [VirusTotal](https://www.virustotal.com/gui/home/upload) to determine if the attachment is malicious or not. However, the attachment payloads appear to be getting stripped, which is changing the MD5 hash of some attachments. This prevents me from accurately looking up these attachments in tools like the one mentioned above.

**To Reproduce**

1. download the .eml file attached to this issue and unzip it
2. using python 3 (i'm using 3.6.9):
```python
import mailparser
f = open('/path/to/example.eml', 'rb')
mail = mailparse.parse_from_bytes(f.read())
f.close()
attachment = mail.attachments[0]

import hashlib
hashlib.md5(attachment.get("payload").encode(attachment.get("charset"))).hexdigest()
# outputs '442972dbdaba2b9c8c742b4e35a61e70'
```

I used the email library to parse the same eml file and found that the payload of the attachment with the email library ended with `</html>\r\n\t=\r\n` where as the payload from the mailparser library ended with `</html>`. 

**Expected behavior**

The correct MD5 hash for the attachment is 'a4546bf059509d6f13a81436214972d7'. I determined this by saving the attachment from the .eml file and using the following powershell:

```powershell
Get-FileHash -Path "C:\path\to\Voicemail Audio.html" -Algorithm MD5

Algorithm       Hash
---------       ----
MD5             A4546BF059509D6F13A81436214972D7
```

**Raw mail**

Attached below is the zipped directory 'example.zip'. Within this directory there is one email file, 'example.eml'. This is an email with an attachment in it. I don't recommend opening the attachment in the email (Voicemail Audio.html) on your machine, I'm unsure of what it does (if anything).

[example.zip](https://github.com/SpamScope/mail-parser/files/4713043/example.zip)

**Environment:**
 - OS: Ubuntu 18.04.4 LTS
 - Docker: no
 - mail-parser version: 3.12.0

**Additional context**

I forked the repo and noticed that the function `ported_string` in `mailparser>utils.py` used the `.strip()` method. I took out all of the `.strip()` method calls in that function and ran the eml file through that 'updated' version and the MD5 came out correct. However, I'm assuming this modification could mess up other things, as I see `ported_string` gets used elsewhere.

**Comment by bleonard252** [comment]
This could potentially be why JPEG "attachments" aren't working. They parse correctly manually, and when I get the string it's already missing some of the JPEG signature, so it has to be a Mail Parser problem. The following is used to open the section in the email:
```
--000000000000c14a0405b74d1cf8
Content-Type: image/jpeg
Content-Disposition: attachment
Content-Transfer-Encoding: base64
```

**Comment by fedelemantuano** [comment]
For @bleonard252 when there is base64 mailparser doesn't change anything.

```
 if transfer_encoding == "base64" or (
                       transfer_encoding == "quoted-\
                       printable" and "application" in mail_content_type):

                        payload = p.get_payload(decode=False)
                        binary = True
```

For @LiamMahoney I tryed to download attachment from my mail client and the fingerprint it's different from mine and yours.
I removed the strip part from that function, but the fingerprint it's different.
I used vimdiff for try to understand. The left part it's mailparser and the right part it's mail client. Change the last line.
I think that it's depend  from python library.
This is a strange case, becouse you have an sample in html. So you could have some different that depend from client.
In binary case, you don't have this issue.

![image](https://user-images.githubusercontent.com/2412951/109126453-886d8c80-774d-11eb-80c8-51a344b8ad03.png)
