### ISSUE TITLE
Charset iso-8859-8-i is not supported (hebrew)

### ISSUE THREAD

**Issue by Rashe** [SpamScope/mail-parser#74]
**Describe the bug**
Email body (text_plain, text_html) contains dots instead of text when  charset="iso-8859-8-i" and Content-Transfer-Encoding: quoted-printable.

**Expected behavior**
Text should be parsed

**Raw mail**
https://gist.github.com/Rashe/2d6887c1d442d51f2bea3c5b0f8cfb6a

**Environment:**
 - OS: Linux
 - Docker: Yes
 - mail-parser version 3.12.0

**Comment by Rashe** [comment]
@fedelemantuano hi, can you please update about the issue? My sprint is almost over and I need to update my tasks :)
Will support of iso-8859-8-i will be added or I need to find some trick about it?

Thx

**Comment by fedelemantuano** [comment]
Hi @Rashe I know but I have others inside issues to manage and I can work on these best effort. But I will work on it soon.

**Comment by Kontra123** [comment]
Hi, any update about it ? i have the same problem

**Comment by Kontra123** [comment]
Hi Fedele Mantuano!
I see u changed the label.
Are you gonna fix it?
if yes, then when?

Thanks!

**Comment by fedelemantuano** [comment]
The mail in this example is malformed: `"MissingHeaderBodySeparatorDefect: Found line with no leading whitespace and no colon before blank line."`

I need to have mail and the errors. I read the email with a client and I had the same result.
Can you explain me better the issue?

**Comment by Kontra123** [comment]
Hi, thanks.

This Hebrew file parsing working- utf-8:
https://file.io/Zw8nO5hKYkpN

This Hebrew file parsing not working- iso-8859-8-i:
https://file.io/dnAzecVJKMLf

**Comment by Kontra123** [comment]
Hi, anymore questions ?

**Comment by fedelemantuano** [comment]
Hi @Kontra123 I need to see di raw mail. The first one is malformed and [here](https://github.com/SpamScope/mail-parser/issues/74#issuecomment-780388816) you sent me parsing.

**Comment by Kontra123** [comment]
I will try to explain more:
search this string below: 
=E0=E7=F8=FA 
in Hebrew it means ("other") - אחרת
How do i know?
I uploaded a file to improve it:
https://gofile.io/d/Rvo5sh

I don't know exactly what's your problem,
I just know that your parser doesn't handle it correctly.
Is it more clear now?

charset="iso-8859-8-i"\nContent-Transfer-Encoding: quoted-printable\n\n=E4=E9 =F8=E5=F0=E9=FA , =F4=F0=E5 =E0=EC=E9 =EB=E1=F8 =EC=E2=E1=E9 =E4=EE=\n=E9=F9=F8=E4 =E5=E4=E0=EE=FA =F8=E7=E5=E1=E5=FA =EE=E0=E5=E3 =F8=E7=E5=F7=\n=E4 =EC=E9. =E0=F9=EE=E7 =E0=E1=EC =EE=E0=E5=E3 =F9=FA=EE=F6=E0=E9 =EC=E9 =\n=E4=E6=E3=EE=F0=E5=FA =E0=E7=F8=FA.\n=F1=E5=F4=F9 =F0=F2=E9=ED.\n=E0=EC=E9=E0=F0=E4\n\nGet Outlook for iOS<https://aka.ms/o0ukef>\n________________________________\nFrom: Ronit Oren (Ethosia HR) <ronit.oren@ethosia.com>\nSent: Thursday, February 11, 2021 8:03:06 PM\nTo: koreneliana@gmail.com <koreneliana@gmail.com>\nSubject: =E4=F6=F2=FA =F2=E1=E5=E3=E4 =EE=E7=E1=F8=FA =E0=FA=E5=F1=E9=E4 - =\n[#2636553#]\n\n\n=E4=E9=E9 =E0=EC=E9=E0=F0=E4,\n\n=EE=E4 =F9=EC=E5=EE=EA?\n\n=F0=F4=FA=E7=E4 =E0=F6=EC=E9 =EE=F9=F8=E4 =F9=EC=E3=F2=FA=E9 =E9=EB=E5=EC=\n=E4 =EE=E0=E5=E3 =EC=E4=FA=E0=E9=ED =EC=EA.\n\n=E4=EE=F9=F8=E4 =E4=E9=F0=E4 =E1=E7=E1=F8=E4 =F9=EE=EE=E5=F7=EE=FA =E1=F8=\n=E7=E5=E1=E5=FA, =E4=ED =EE=E7=F4=F9=E9=ED  Global Clinical Trial Manager.\n\n=F7=E9=F9=E5=F8 =EC=EE=F9=F8=E4: https://www.ethosia.co.il/content/global-c=\nlinical-trial-manager\n=E5=F2=EB=F9=E9=E5 =F2=ED =E4=F7=E9=F9=E5=F8 :)\n\n=EE=E4 =E3=F2=FA=EA?\n\n=E0=F4=F9=F8 =EC=E4=F2=E1=E9=F8 =EC=E4=ED =E0=FA =E4=F7=E5=F8=E5=FA =E7=E9=\n=E9=ED =F9=EC=EA?\n\n\n=E0=F0=E9 =EB=EE=E5=E1=EF =EC=F8=F9=E5=FA=EA.\n\n\n=FA=E5=E3=E4 =E5=E9=E5=ED =F0=F4=EC=E0,\n\n=F8=E5=F0=E9=FA.\n\n#_##__2636553__##_#\n\n\

**Comment by fedelemantuano** [comment]
I have the same error with the mail client. Maybe this test email is malformed.
If you have another error with another email, please open a new issue.

![image](https://user-images.githubusercontent.com/2412951/109333134-564c4f80-785f-11eb-90ad-4f236d77b5c5.png)
