### ISSUE TITLE
headers_raw is None

### ISSUE THREAD

**Issue by Henner** [SpamScope/mail-parser#77]
**Describe the bug**
Documentation says every property has a name_raw and a name_json property. For headers headers_raw is None while headers_json is a valid json object

**To Reproduce**
1. `import mailparser`
2. `mail = mailparser.parse_from_file(f)`
3. `print(mail.headers_raw)`

**Expected behavior**
Get a string of all mail headers

**Environment:**
 - OS: Windows
 - Docker: no
 - mail-parser version 3.12.0
 - python version 3.8.6rc1

**Comment by fedelemantuano** [comment]
I can't test this issue:

```
Raw mail The raw mail to reproduce the behavior. You can use a gist. The issues without raw mail will be closed.
```
