### ISSUE TITLE
write_attachments fails if attachment filename contains invalid characters - which is common.

### ISSUE THREAD

**Issue by Sunny-Engineer** [SpamScope/mail-parser#78]
**Describe the bug**
When processing a file that has an attachment that is an email "eml" file, or any other file that contains invalid characters, the routine fails with the message:

[Errno 22] Invalid argument: 'd:/American Family Care Mentor,\r\n Ohio.eml']

**To Reproduce**
Process any of the attached email files.

**Expected behavior**
It should remove illegal characters.

**Raw mail**
The raw mail to reproduce the behavior.
You can use a `gist` like [this](https://gist.github.com/fedelemantuano/5dd702004c25a46b2bd60de21e67458e).
The issues without raw mail will be closed.

**Environment:**
 - OS: [ Windows]
 - Docker: [no]
 - mail-parser version [3.12.0]

**Additional context**

Traceback (most recent call last):
  File "D:/BREmailAttachmentExtract.py", line 325, in <module>
    mail.write_attachments("d:/")
  File "C:\\Python\Python37\lib\site-packages\mailparser\mailparser.py", line 486, in write_attachments
    base_path=base_path)
  File "C:\\Python\Python37\lib\site-packages\mailparser\utils.py", line 537, in write_attachments
    filename=a["filename"],
  File "C:\Python\Python37\lib\site-packages\mailparser\utils.py", line 558, in write_sample
    with open(sample, "wb") as f:
OSError: [Errno 22] Invalid argument: 'd:/American Family Care Mentor,\r\n Ohio.eml'

[TestEmailFiles.zip](https://github.com/SpamScope/mail-parser/files/5316339/TestEmailFiles.zip)

**Comment by fedelemantuano** [comment]
I tested your examples with actual develop branch without any errors.
Maybe the error is only for Windows or it was fixed.
