### ISSUE TITLE
Charset iso-8859-8-i is not supported (hebrew) - with more details included text files and photos

### ISSUE THREAD

**Issue by Kontra123** [SpamScope/mail-parser#86]
Iso-8859-8-i parsing not working.
Utf-8 parsing working.

Attached txt files of "email" parsing:
print(key_values['email']):

attached files with example:

Iso-8859-8-i txt (corrupt):
https://textuploader.com/18pyy

Iso-8859-8-i view after parsing (corrupt):
https://pasteboard.co/JQraMYX.png

Iso-8859-8-i view without parsing using Cybo (working):
https://pasteboard.co/JQr0G2L.png

utf-8 parsing txt (working):
https://textuploader.com/18pyb

utf-8 after parsing view (working):
https://pasteboard.co/JQrb6tw.png

**Comment by fedelemantuano** [comment]
I should close this issue because it doesn't follow the template.

**Comment by Kontra123** [comment]
What is the template ?

**Comment by fedelemantuano** [comment]
When click new issue there is a template compiled. You should follow it.
