### ISSUE TITLE
Parsing in iso-8859-8-i format not working for Hebrew chars,

### ISSUE THREAD

**Issue by Kontra123** [SpamScope/mail-parser#87]
**Describe the bug**
In incoming mail which is encoded in iso-8859-8-i (e.g. from yahoo), the parsed text doesn't display the Hebrew characters.  

**To Reproduce**
`import mailparser`
 'key_values = parse.key_values()'
`parsed_data = mailparser.parse_from_string(key_values['email'])

**Expected behavior**
Decode text encoded in iso-8859-8-i and display all characters in the parsed text.

**Raw mail for  iso-8859-8-i**
https://textuploader.com/182ht

Bad view result: 
https://pasteboard.co/JRuHDaM.png

Expected view result:
https://pasteboard.co/JRuImu5.png

**example for working raw file in utf-8:**

good txt file:
https://textuploader.com/18pyb.

good view result:
https://pasteboard.co/JQrb6tw.png

**Environment:**
 - OS:  Windows
 - Docker: yes
 - mail-parser version 3.12.0

**Comment by Kontra123** [comment]
Hi, any news about it ?

**Comment by hrtlik** [comment]
I ran into same problem. Version 3.15.0 is causing the problems, 3.14.0 is working fine.

**Comment by fedelemantuano** [comment]
I tested this email with `3.15.0` and `3.14.0` with same results.

mailparser uses [email.header.decode_header](https://docs.python.org/3/library/email.header.html#email.header.decode_header) of Python standard library to parse header. In documentation it's not clean but in code of this function you can read:

```
    """Decode a message header value without converting charset.

    Returns a list of (string, charset) pairs containing each of the decoded
    parts of the header.  Charset is None for non-encoded parts of the header,
    otherwise a lower-case string containing the name of the character set
    specified in the encoded string.

    header may be a string that may or may not contain RFC2047 encoded words,
    or it may be a Header object.

    An email.errors.HeaderParseError may be raised when certain decoding error
    occurs (e.g. a base64 decoding exception).
    """
```

So I think that uses [RFC2047](https://datatracker.ietf.org/doc/html/rfc2047) that doesn't have `iso-8859-8-i`.

I think that it is a limit of Python Standard library.
