### ISSUE TITLE
parse_from_bytes raises UnicodeDecodeError

### ISSUE THREAD

**Issue by Itay4** [SpamScope/mail-parser#88]
**Describe the bug**
passing an email that contains `C:\Users` to `parse_from_bytes()` raises `UnicodeDecodeError: 'rawunicodeescape' codec can't decode bytes in position 2019-2020: truncated \UXXXXXXXX escape`
issue was resolved by using a replace:
```python
message_bytes.replace(b'\\', b'/')
```

**Environment:**
 - OS: Linux
 - Docker: yes
 - mail-parser version 3.15.0

**Additional context**
issue was introduced in https://github.com/SpamScope/mail-parser/pull/84

**Comment by fedelemantuano** [comment]
I'm not sure about this issue because I don't have any email to test, but I try to do this.

```
msg = open('/tmp/mail.eml','rb').read()
type(msg)
```
So `msg` is a byte object with `C:\Users` as subject.

Then

```
m = mailparser.parse_from_bytes(msg)
m.subject
```

Result

```
C:\\Users
```

I think that you are not passing `bytes` or you have another issue that not in `mailparser`.
