### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by ajurna** [SpamScope/mail-parser#9]
Hello.

I have found an error with the parser when it tries to find who it was delivered to and the field is missing.

      File "C:\project\dashboard\management\commands\mail_service.py", line 90, in check_mail_by_id
        headers = mailparser.parse_from_bytes(response_part[1])
      File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 73, in parse_from_bytes
        return MailParser.from_bytes(bt).parse()
      File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 297, in parse
        self._make_mail()
      File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 217, in _make_mail
        "to": self.to_,
      File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 383, in to_
        self.message.get('to', self.message.get('delivered-to')))
      File "C:\project\venv\lib\site-packages\mailparser\utils.py", line 80, in decode_header_part
        for d, c in decode_header(header):
      File "C:\Python36\Lib\email\header.py", line 80, in decode_header
        if not ecre.search(header):
    TypeError: expected string or bytes-like object

**Comment by fedelemantuano** [comment]
Hi,
which version of mailparser are you using?

**Comment by ajurna** [comment]
mail-parser==1.2.1

**Comment by fedelemantuano** [comment]
You could send me a mail on 

> mantuano.fedele at gmail.com

Is _response_part[1]_ a byte type? Did you try with _mailparser.parse_from_string_?

**Comment by ajurna** [comment]
i use pycharm and looked through it with the debugger.
code is below. the data inspected was of bytes type
this is in python3.6 and i forwarded you the unsanitised data to your email

    def check_mail_by_id(self, message_id: AnyStr) -> mailparser.MailParser:
        _, header_data_raw = self.imap.fetch(message_id, '(BODY.PEEK[HEADER])')
        for response_part in header_data_raw:
            if isinstance(response_part, tuple):
                headers = mailparser.parse_from_bytes(response_part[1])
                return headers

**Comment by fedelemantuano** [comment]
In your header there isn't the _to_:

> File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 217, in _make_mail
>     "to": self.to_,
>   File "C:\project\venv\lib\site-packages\mailparser\mailparser.py", line 383, in to_
>     self.message.get('to', self.message.get('delivered-to')))

So the parsing fails because the email should have _to_.

Are you sure that you take all email with _self.imap.fetch_.
mailparser works with all raw mail.

**Comment by ajurna** [comment]
well i'm parsing the headers first. You can see that i'm using the BODY,PEEK[HEADER] in the fetch
this mail when i checked in outlook didn't have anyone in the to section either.
the only thing missing should be the body of the mail.

**Comment by fedelemantuano** [comment]
The best way is:

- Get all mail, and put it in a variable
- Check with print the header (only for debug)
- I could fix this problem, but the mail should have a `to ` in the headers

The code part is [this](https://github.com/SpamScope/mail-parser/blob/develop/mailparser/mailparser.py#L383).

**Comment by ajurna** [comment]
i saw that. my issue is that this mail doesn't have a deliviered-to header. which makes the parser fail.
the mail is being read by imap from office365.
i don't want to pull the full mails as in my use case i'm accessing my own inbox and it's simpler to not have to mark everything unread again.

**Comment by fedelemantuano** [comment]
Ok, you can take only headers, and mailparser should work fine because there are mails without body or attachments.
In your mail there aren't `to` and `deliviered-to header`, because `deliviered-to header` is the fallback of `to`.
You can try to catch `TypeError` and print headers. Then post here obfuscated hearders, so I can check.

**Comment by ajurna** [comment]
that's why i emailed you the headers.

**Comment by fedelemantuano** [comment]
Fixed with [commit 0219562c84de32d63deb10417278380063337024](https://github.com/SpamScope/mail-parser/commit/0219562c84de32d63deb10417278380063337024)
