### ISSUE TITLE
Intergration with MISP

### ISSUE THREAD

**Issue by vedd3r** [SpamScope/mail-parser#92]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
It will be very beneficial and helpful if SpamScope integrated with [MISP ](https://www.misp-project.org/). Individual emails create an event and parsed data are store in MISP Object following MISP [Standards](https://www.misp-standard.org).

**Describe alternatives you've considered**
Mail2MISP is the closest, however, it is tailored more towards collecting IOCs shared in emails. It has a spamtrap function but I think SpamScope does a better job.

**Additional context**
This will be very useful to CTI - collecting, gathering and correlating spam trap data directly in MISP.

**Comment by fedelemantuano** [comment]
@vedd3r can you help me to integrate SpamScope mailparser in MISP?

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
