### ISSUE TITLE
Empty metadata when using mail-parser to parse .msg outlook emails (email-​outlook-message-perl 0.918-2)

### ISSUE THREAD

**Issue by alealbonico** [SpamScope/mail-parser#93]
While working with python (no matter the version), I noticed it's not possible to extract metadata from an outlook email (.msg) if you have email-​outlook-message-perl 0.918-2 installed. Instead, you'll need to use version 0.919-1, but updating it can be quite troublesome.

While trying to do so in this repository, some errors would occur. This drove me to look for a .deb file of the latter version mentioned, which I found here:

http://ftp.debian.org/debian/pool/main/libe/libemail-outlook-message-perl/

After downloading it, I installed it with the following command:

`dpkg -i [name_of_file]`

Everything worked fine after that.

**Comment by fedelemantuano** [comment]
Thanks for suggest. This is not issue of `mail-parser` but it's depends from your local system, but we can change `Dockerfile` to update it with the new `email-​outlook-message-perl` library.

**Comment by fedelemantuano** [comment]
To review in the new version.
I will open a new issue if needed.
