### ISSUE TITLE
Issue when parsing an email message

### ISSUE THREAD

**Issue by James-Hudson3010** [SpamScope/mail-parser#94]
When parsing the attached email message, I received the following messages:

```
More than one match found for (?:by\s+(?P<by>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+with(?! cipher)|\s+id|\s+for|\s+via|;)) in majordomo@vger.kernel.org by vger.kernel.org via listexpand id S230171AbhFJIbY ORCPT <rfc822;bruce@untroubled.org> ; Thu, 10 Jun 2021 04:31:24 -0400

More than one match found for (?:by\s+(?P<by>.+?)(?:\s*[(]?envelope-from|\s*[(]?envelope-sender|\s+from|\s+with(?! cipher)|\s+id|\s+for|\s+via|;)) in majordomo@vger.kernel.org by vger.kernel.org via listexpand id S230171AbhFJIbY ORCPT <rfc822;bruce@untroubled.org> ; Thu, 10 Jun 2021 04:31:24 -0400
```

This email message came from a spam archive ( http://untroubled.org/spam/ ) -- http://untroubled.org/spam/2021-06.7z

**Comment by James-Hudson3010** [comment]
Attached wrong message...here is the correct one.

[1623336582.1677509_17.txt](https://github.com/SpamScope/mail-parser/files/6656630/1623336582.1677509_17.txt)

**Comment by fedelemantuano** [comment]
It's not an issue. There isn't a standard to parse the received headers, so I print this message to tuning this regex. Thanks for submission.
